# Generated by Django 4.2 on 2023-10-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleMessage',
        ),
        migrations.AddField(
            model_name='message',
            name='replyTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chatroom.message'),
        ),
    ]
