# Generated by Django 4.2 on 2023-10-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0002_initial'),
        ('chatroom', '0003_delete_singlemessage_message_replyto'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='joinedFiles',
            field=models.ManyToManyField(blank=True, related_name='messages', to='mediacenter.filesmodel'),
        ),
    ]
