# Generated by Django 4.2 on 2023-11-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0006_chatroom_companytype_chatroom_geography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='companyType',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='industry',
        ),
    ]
