# Generated by Django 4.2 on 2023-11-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0007_remove_chatroom_companytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='companyType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='geography',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
